from typing import List, Dict, Any

SEED_PRODUCTS: List[Dict[str, Any]] = [
    {
        "id": "lihas-rng-01",
        "name": "Pavé Cuban Curb Spinner Ring",
        "category": "Rings",
        "price": 399,
        "description": "Forged from surgical 316L anti-tarnish stainless steel with a kinetic micro-pavé Cuban link spinner core. Completely waterproof, sweatproof, and designed for mindful fidgeting with timeless aesthetics.",
        "material": "316L Surgical Steel & Flawless Zirconia",
        "color": "Polished Silver / Clear Pavé",
        "style": "Kinetic Luxury Streetwear",
        "image_url": "/adii3.jpeg",
        "gallery": ["/adii3.jpeg", "/adii4.jpeg", "/adii2.jpeg"],
        "sizes": ["US 7", "US 8", "US 9", "US 10"],
        "rating": 4.9,
        "reviews_count": 168,
        "stock": 45,
        "is_active": True,
        "is_new": True,
        "is_trending": True,
        "created_at": "2026-09-01T00:00:00Z",
    },
    {
        "id": "lihas-nck-01",
        "name": "Greek Meander Gold Barrel Chain",
        "category": "Necklaces",
        "price": 499,
        "description": "Triple-dipped 18K gold barrel pendant intricately laser-etched with the Hellenic meander fret pattern, framed by handset crystal pavé borders on a heavy box link chain.",
        "material": "18K Champagne Gold on Anti-Tarnish Steel",
        "color": "Champagne Gold & Brilliant Crystal",
        "style": "Modern Grecian Heritage",
        "image_url": "/adii2.jpeg",
        "gallery": ["/adii2.jpeg", "/adii3.jpeg", "/adii5.jpeg"],
        "sizes": ["50 cm", "55 cm"],
        "rating": 5.0,
        "reviews_count": 224,
        "stock": 38,
        "is_active": True,
        "is_new": True,
        "is_trending": True,
        "created_at": "2026-09-01T00:00:00Z",
    },
    {
        "id": "lihas-ear-01",
        "name": "Midnight Onyx Halo Solitaire Stud",
        "category": "Earrings",
        "price": 399,
        "description": "Deep high-refraction jet black mineral center encircled with a delicate halo of micro-brilliant pavé crystals. Fitted with an ultra-comfortable hypoallergenic backing.",
        "material": "Natural Jet Onyx Mineral & Rhodium Finish",
        "color": "Obsidian Black & Ice Pavé",
        "style": "Dark Minimalist Statement",
        "image_url": "/adii1.jpeg",
        "gallery": ["/adii1.jpeg", "/adii.jpeg", "/adii2.jpeg"],
        "sizes": ["8 mm Standard"],
        "rating": 4.9,
        "reviews_count": 98,
        "stock": 60,
        "is_active": True,
        "is_new": True,
        "is_trending": True,
        "created_at": "2026-09-01T00:00:00Z",
    },
    {
        "id": "lihas-rng-02",
        "name": "Matte Circuit Geometric Titanium Band",
        "category": "Rings",
        "price": 399,
        "description": "Precision laser-engraved cybernetic topography lines onto a brushed matte obsidian black band. Ultra-light titanium alloy designed for effortless daily rotation.",
        "material": "Matte PVD Titanium Steel",
        "color": "Matte Obsidian Black",
        "style": "Cyberpunk Precision Minimalist",
        "image_url": "/adii4.jpeg",
        "gallery": ["/adii4.jpeg", "/adii3.jpeg", "/adii5.jpeg"],
        "sizes": ["US 7", "US 8", "US 9", "US 10"],
        "rating": 4.8,
        "reviews_count": 84,
        "stock": 52,
        "is_active": True,
        "is_new": False,
        "is_trending": True,
        "created_at": "2026-09-01T00:00:00Z",
    },
    {
        "id": "lihas-nck-02",
        "name": "Obsidian Spider Bead Necklace",
        "category": "Necklaces",
        "price": 549,
        "description": "Hand-strung faceted gloss-black onyx ball beads paired with a bespoke architectural spider silhouette pendant. High-impact modern streetwear statement.",
        "material": "Black Onyx Beads & PVD Coated Stainless Steel",
        "color": "Gloss Jet Black & Gunmetal",
        "style": "Gothic Architectural Streetwear",
        "image_url": "/adii5.jpeg",
        "gallery": ["/adii5.jpeg", "/adii4.jpeg", "/adii3.jpeg"],
        "sizes": ["55 cm", "60 cm"],
        "rating": 4.9,
        "reviews_count": 147,
        "stock": 30,
        "is_active": True,
        "is_new": True,
        "is_trending": True,
        "created_at": "2026-09-01T00:00:00Z",
    },
    {
        "id": "lihas-clp-01",
        "name": "Brushed Steel Industrial Disc Ear Clip",
        "category": "Ear Clips",
        "price": 449,
        "description": "Minimalist industrial disc clip designed for non-pierced ears or high helix positions. Features a secure tension screw clamp that stays comfortably snug all day.",
        "material": "Solid Brushed 316L Stainless Steel",
        "color": "Industrial Brushed Silver",
        "style": "Industrial Minimalist Non-Pierced",
        "image_url": "/adii.jpeg",
        "gallery": ["/adii.jpeg", "/adii1.jpeg", "/adii4.jpeg"],
        "sizes": ["Universal Adjustable Fit"],
        "rating": 4.8,
        "reviews_count": 79,
        "stock": 40,
        "is_active": True,
        "is_new": True,
        "is_trending": False,
        "created_at": "2026-09-01T00:00:00Z",
    },
]
